from selenium.webdriver.common.by import By


class DoskaLocators:
    LOGIN_AND_REGISTRATION_BUTTON = (By.XPATH, "//button[text()='Вход и регистрация']")
    NOT_ACCOUNT_BUTTON = (By.XPATH, "//button[text()='Нет аккаунта']")
    EMAIL_INPUT = (By.NAME, "email")
    PASSWORD_INPUT = (By.NAME, "password")
    SUBMIT_PASSWORD_INPUT = (By.NAME, "submitPassword")
    CREATE_ACCOUNT_BUTTON = (By.XPATH, "//button[text()='Создать аккаунт']")
    AVATAR = (By.CSS_SELECTOR, ".svgSmall")
    USER_NAME = (By.CLASS_NAME, "profileText")
    INPUT_BORDER_ERROR = (By.CSS_SELECTOR, ".input_inputError__fLUP9")
    TEXT_ERROR = (By.XPATH, "//form/div[2]/div[1]/span[@class='input_span__yWPqB']")
    EXIT_BUTTON = (By.XPATH, "//button[contains(text(),'Выйти')]")
    LOGIN_BUTTON = (By.XPATH, "//button[text()='Войти']")
    POST_AD_BUTTON = (By.XPATH, "//button[text()='Разместить объявление']")
    POST_AD_FORM = (By.XPATH, "//form[@class='popUp_shell__LuyqR']")
    POST_FORM_TEXT = (By.XPATH, "//h1[text()='Чтобы разместить объявление, авторизуйтесь']")
    PUBLISH_BUTTON = (By.XPATH, "//button[text()='Опубликовать']")
    PRODUCT_NAME_INPUT = (By.NAME, "name")
    PRODUCT_DESCRIPTION_TEXTAREA = (By.XPATH, "//textarea[@class='textarea_inputStandart__IoNxq spanGlobal']")
    PRODUCT_PRICE_INPUT = (By.NAME, "price")
    CATEGORY_DROPDOWN = (By.XPATH, "//button[@class='dropDownMenu_arrowDown__pfGL1 dropDownMenu_noDefault__wSKsP']")
    BOOKS_BUTTON_FROM_CATEGORY = (By.XPATH, "//span[text()='Книги']")
    CITY_DROPDOWN = (By.XPATH, "//form/div[3]/div[1]/button[@class='dropDownMenu_arrowDown__pfGL1 dropDownMenu_noDefault__wSKsP']")
    N_NOVGOROD_BUTTON_FROM_CITY = (By.XPATH, "//span[text()='Нижний Новгород']")
    RADIO_BUTTON = (By.XPATH, "//div[@class='radioUnput_inputRegular__FbVbr']")
    MY_ADS_TEXT = (By.XPATH, "//h1[@class='h1']")
    CARD_EXIST = (By.CLASS_NAME, "card")
